name: ci
on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        ghc: ['9.6.2']
    steps:
    - uses: actions/checkout@v3
    - uses: haskell/actions/setup@v2
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: 'latest'
    - uses: actions/cache@v3
      name: Cache cabal stuff
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc }}-
    - name: Build without sparse
      run: |
        cabal configure --enable-tests --enable-benchmarks --benchmark-option=-l -f-sparse --ghc-options='-fcheck-prim-bounds' --constraint 'vector +unsafechecks +internalchecks'
        cabal build --write-ghc-environment-files=always
        cabal test
        cabal bench
        cabal haddock
    - name: Build with sparse
      run: |
        cabal configure --enable-tests --enable-benchmarks --benchmark-option=-l --ghc-options='-fcheck-prim-bounds' --constraint 'vector +unsafechecks +internalchecks'
        cabal build --write-ghc-environment-files=always
        cabal test
        cabal bench
        cabal haddock
    - name: Sdist
      run: cabal sdist
