name: ci
on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        ghc: ['8.2', '8.4', '8.6', '8.8', '8.10', '9.0']
        include:
        - os: windows-latest
          ghc: 'latest'
        - os: macOS-latest
          ghc: 'latest'
    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: 'latest'
    - uses: actions/cache@v2.1.4
      name: Cache cabal stuff
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc }}-
    - name: Build without sparse
      run: |
        cabal configure --enable-tests --enable-benchmarks --benchmark-option=-l -f-sparse
        cabal build --write-ghc-environment-files=always
        cabal test
        cabal bench
        cabal haddock
    - name: Build with sparse
      run: |
        cabal configure --enable-tests --enable-benchmarks --benchmark-option=-l
        cabal build --write-ghc-environment-files=always
        cabal test
        cabal bench
        cabal haddock
    - name: Sdist
      run: cabal sdist
